### ISSUE TITLE
Run black on generated output

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/roboswag#20]
Could it be possible to run black from python on generated class? We're trying to match the format using Jinja templates (and it even spread in multi lines if line is too long) but it's still not perfect. We can minimize the effort on our side if we were able to use external formatter (ie the whole `` get_python_method_signatur`` in endpoint.py could be a lot less complex).

**Comment by bhirsz** [comment]
@mnojek Did you perhaps completed it already? I saw blackfiy methods in the code.

**Comment by mnojek** [comment]
Yes, it blackifies the files already here: `roboswag/generate/generate.py#L40`

**Comment by bhirsz** [comment]
Since it's implemented, closing the issue.
