### ISSUE TITLE
Support for OpenAPI v3

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/roboswag#24]
The `APIModel` class only supports OpenAPI version 2, while `prance` that is used for parsing the API is able to analyze also v3. We need to add different methods for parsing swagger v3.

**Comment by bhirsz** [comment]
The simplest out of the box support for OpenAPI v3 can be done if we update ``swagger["definitions"]`` to ``swagger["components"]["schemas"]`` in our code. There could be a lot of other stuff missing but it was enough to parse OpenAPi v3 file generated from FastApi example application.

I will update our code
